# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
#
# See https://github.com/r-lib/actions/tree/master/examples#readme for
# additional example workflows available for the R community.

name: R

on:
  push:
    branches: [ "main", "github-actions-build" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch: 
  
permissions:
  contents: read

jobs:
  builder:
    runs-on: ${{ matrix.config.os }}
    name: ${{ matrix.config.os }} (${{ matrix.config.r }})
    strategy: 
      fail-fast: false
      matrix:
        config:
          - {os: windows-latest, r: '4.1'}
          - {os: ubuntu-latest, r: 'release'}
          - {os: macos-latest, r: 'release'}
    env: 
        R_KEEP_PKG_SOURCE: yes
    steps:
      # see this for details: https://msmith.de/2020/03/12/r-cmd-check-github-actions.html
      - name: Configure git
        run: git config --global core.autocrlf false
      - uses: actions/checkout@v3
      - uses: r-lib/actions/setup-pandoc@v2
      - uses: r-lib/actions/setup-tinytex@v2
      - uses: r-lib/actions/setup-r@v2
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          cache-version: 2
          extra-packages: |
            any::ggplot2
            any::rcmdcheck
            any::roxygen2
          needs: |
            check
            roxygen2
      - name: Install gsl
        if: runner.os == 'macOS'
        run: |
          brew install gsl

      - name: Build package
        if: runner.os == 'Windows'
        shell: cmd
        run: R CMD build .
      - name: Build package
        if: runner.os == 'Linux' || runner.os == 'macOs' 
        run: R CMD build .
      - name: Test Install
        if: runner.os == 'Windows'
        shell: cmd
        run: R CMD INSTALL ToxicR_23.4.1.1.0.tar.gz
      - name: Test Install
        if: runner.os == 'Linux' || runner.os == 'macOs'
        run: R CMD INSTALL ToxicR_23.4.1.1.0.tar.gz
      - name: Upload package
        uses: actions/upload-artifact@v3
        with:
          path: ToxicR_23.4.1.1.0.tar.gz
          name: ToxicR_23.4.1.1.0-${{ matrix.config.os }}.${{ matrix.config.r }}.tar.gz