# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
#
# See https://github.com/r-lib/actions/tree/master/examples#readme for
# additional example workflows available for the R community.

name: R

on:
  push:
    branches: [ "github-actions-build" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch: 
  
permissions:
  contents: read

jobs:
  builder:
    runs-on: ${{ matrix.config.os }}
    name: ${{ matrix.config.os }} (${{ matrix.config.r }})
    strategy: 
      fail-fast: false
      matrix:
        config:
          - {os: windows-latest, r: '4.1'}
          - {os: ubuntu-latest, r: 'release'}
          - {os: macos-latest, r: 'release'}
    env: 
        R_KEEP_PKG_SOURCE: yes
    steps:
      # see this for details: https://msmith.de/2020/03/12/r-cmd-check-github-actions.html
      - name: Configure git
        run: git config --global core.autocrlf false
      - uses: actions/checkout@v3
      - uses: r-lib/actions/setup-pandoc@v2
      - uses: r-lib/actions/setup-tinytex@v2
      - uses: r-lib/actions/setup-r@v2
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          cache-version: 2
          extra-packages: |
            any::ggplot2
            any::rcmdcheck
            any::roxygen2
          needs: |
            check
            roxygen2
      - name: Install dependencies
        if: runner.os == 'Linux'
        run: |
          sudo apt-get install -y r-base-dev

      - name: Build package
        shell: cmd
        run: R CMD build .
      - name: Test Install
        shell: cmd
        run: R CMD INSTALL ToxicR_23.4.1.1.0.tar.gz
      # - name: Create manuals
      #   shell: cmd
      #   run: R CMD Rd2pdf --encoding=UTF-8 --no-preview --no-clean ToxicR_23.4.1.1.0.tar.gz
      # - name: Document
      #   run: roxygen2::roxygenise()
      #   shell: Rscript {0}
      # - name: Check Win
      #   run: devtools::check_win_release()
      #   shell: Rscript {0}
      # - uses: r-lib/actions/check-r-package@v2
      - name: Upload package
        uses: actions/upload-artifact@v3
        with:
          path: ToxicR_23.4.1.1.0.tar.gz
          name: ToxicR_23.4.1.1.0-${{ matrix.config.os }}.${{ matrix.config.r }}.tar.gz

  # build-linux:
  #   runs-on: ubuntu-latest
  #   strategy:
  #     matrix:
  #       r-version: ['4.2.0']
  #   steps:
  #     - uses: actions/checkout@v3
  #     - uses: r-lib/actions/setup-pandoc@v2
  #     - uses: r-lib/actions/setup-r@v2
  #     - uses: r-lib/actions/setup-tinytex@v2
  #     - uses: r-lib/actions/setup-r-dependencies@v2
  #       with:
  #         cache-version: 2
  #         extra-packages: |
  #           any::ggplot2
  #           any::rcmdcheck
  #     - name: Build package
  #       run: R CMD build .
  #     - uses: r-lib/actions/check-r-package@v2
  #       with:
  #         args: 'c("--as-cran")'
  #     - name: Upload package
  #       uses: actions/upload-artifact@v3
  #       with:
  #         name: ToxicR_23.4.1.1.0-deb.tar.gz
  #         path: ToxicR_23.4.1.1.0.tar.gz